//
//  UserLoginModels.swift
//  BankOfEveris
//
//  Created by Leandro Roberto Medeiros on 12/04/19.
//  Copyright (c) 2019 Leandro Roberto Medeiros. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct LoginResponse: Codable {
    var userAccount: UserAccount?
    var error: Error?
    
    struct UserAccount: Codable {
        var id      : Int = 0
        var name    : String?
        var agency  : String?
        var account : String?
        var balance : Double?
        
        private enum CodingKeys: String, CodingKey {
            case id      = "userId"
            case name
            case agency
            case account = "bankAccount"
            case balance
        }
    }
    
    struct Error: Codable {
        var message: String?
    }
}
