//
//  UserLoginWorker.swift
//  BankOfEveris
//
//  Created by Leandro Roberto Medeiros on 12/04/19.
//  Copyright (c) 2019 Leandro Roberto Medeiros. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

typealias responseHandler = (_ response: LoginResponse) -> ()

class LoginWorker {
    let url: String = "https://bank-app-test.herokuapp.com/api/login"
    
    func getUserData(parameters: [String: String], responseRequest: @escaping(responseHandler)) {
        Alamofire.request(url, method: .post, parameters: parameters, encoding: JSONEncoding.default).responseJSON(completionHandler: {
            response in
            
            switch response.result {
                case .success(_):
                    do {
                        let loginResponse = try JSONDecoder().decode(LoginResponse.self, from: response.data!)
                    
                        responseRequest(loginResponse)
                    } catch (let error) {
                        print(error)
                    }
                case .failure(let error):
                    print(error)
            }
        })
    }
}
