//
//  UserLoginRouter.swift
//  BankOfEveris
//
//  Created by Leandro Roberto Medeiros on 12/04/19.
//  Copyright (c) 2019 Leandro Roberto Medeiros. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UserLoginRoutingLogic{
    func routeTosegueUserExtractViewControllerWithSegue(_ segue: UIStoryboardSegue?)
}

protocol UserLoginDataPassing{
    var dataStore: UserLoginDataStore? { get }
}

class UserLoginRouter: NSObject, UserLoginRoutingLogic, UserLoginDataPassing{
    weak var viewController: UserLoginViewController?
    var dataStore: UserLoginDataStore?
    
    func routeTosegueUserExtractViewControllerWithSegue(_ segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationViewController = segue.destination as! UserExtractViewController
            var destinationDataStore = destinationViewController.router!.dataStore!
            
            sendAccountInformation(source: dataStore!, destination: &destinationDataStore)
        }
    }
    
    func navigateToExtractView(source: UserLoginViewController, destination: UserExtractViewController) {
        source.show(destination, sender: nil)
    }
    
    func sendAccountInformation(source: UserLoginDataStore, destination: inout UserExtractDataStore) {
        destination.userAccount = source.userAccount
    }
}

