//
//  UserLoginPresenter.swift
//  BankOfEveris
//
//  Created by Leandro Roberto Medeiros on 12/04/19.
//  Copyright (c) 2019 Leandro Roberto Medeiros. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserLoginPresentationLogic{
    func showCustomAlert(title: String, message: String) -> Void
    func login(loginResponse: LoginResponse) -> Void
}

class UserLoginPresenter: UserLoginPresentationLogic{
    weak var viewController: UserLoginDisplayLogic?
    
    func showCustomAlert(title: String, message: String) {
        let customAlert = UIAlertController(title: title, message: message, preferredStyle: .alert)
        customAlert.addAction(UIAlertAction(title: "Tentar Novamente!", style: .cancel, handler: nil))
        
        viewController?.failure(alertController: customAlert)
    }
    
    func login(loginResponse: LoginResponse) {
        viewController?.success(userData: loginResponse)
    }
}
