//
//  UserExtractModels.swift
//  BankOfEveris
//
//  Created by Leandro Roberto Medeiros on 12/04/19.
//  Copyright (c) 2019 Leandro Roberto Medeiros. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct ExtractResponse: Codable {
    var extractData: [ExtractData]
    var error: Error?
    
    private enum CodingKeys: String, CodingKey {
        case extractData = "statementList"
    }
    
    struct ExtractData: Codable {
        var title: String?
        var description: String?
        var date: String?
        var value: Double?
        
        private enum CodingKeys: String, CodingKey {
            case title
            case description = "desc"
            case date
            case value
        }
    }
    
    struct Error: Codable {
        var message: String?
    }
}
