//
//  UserExtractRouter.swift
//  BankOfEveris
//
//  Created by Leandro Roberto Medeiros on 12/04/19.
//  Copyright (c) 2019 Leandro Roberto Medeiros. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UserExtractRoutingLogic {
    
}

protocol UserExtractDataPassing {
    var dataStore: UserExtractDataStore? { get }
}

class UserExtractRouter: NSObject, UserExtractRoutingLogic, UserExtractDataPassing {
    weak var viewController: UserExtractViewController?
    var dataStore: UserExtractDataStore?
}
