//
//  UserExtractInteractor.swift
//  BankOfEveris
//
//  Created by Leandro Roberto Medeiros on 12/04/19.
//  Copyright (c) 2019 Leandro Roberto Medeiros. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserExtractBusinessLogic {
    func checkExistentUser() -> Bool
    func getExtractListByUser(userId: String) -> Void
    func getUserAccountData() -> Void
    func clearUserDefaults() -> Void
}

protocol UserExtractDataStore {
    var userAccount: LoginResponse.UserAccount? { get set }
}

class UserExtractInteractor: UserExtractBusinessLogic, UserExtractDataStore {
    var loginResponse: LoginResponse?
    var userAccount: LoginResponse.UserAccount?
    var presenter: UserExtractPresentationLogic?
    var worker: UserExtractWorker?
  
    func getExtractListByUser(userId: String) {
        worker = UserExtractWorker()
        
        worker?.getExtractList(extractId: userId, responseRequest: { response in
            self.presenter?.presentExtractList(extract: response.extractData)
        })
    }
    
    // MARK: Present user account information
    func checkExistentUser() -> Bool {
        return UserDefaults.standard.bool(forKey: "user")
    }
    
    func getUserAccountData() {
        if let userAccount = self.userAccount {
            self.presenter?.presentUserAccountData(userAccountData: userAccount)
        }
    }
    
    // MARK: Clear user inside UserDefaults
    func clearUserDefaults() {
        let userDefaults = UserDefaults.standard
        userDefaults.removeObject(forKey: "user")
        userDefaults.synchronize()
    }
}
