//
//  UserExtractPresenter.swift
//  BankOfEveris
//
//  Created by Leandro Roberto Medeiros on 12/04/19.
//  Copyright (c) 2019 Leandro Roberto Medeiros. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserExtractPresentationLogic{
    func presentUserAccountData(userAccountData: LoginResponse.UserAccount) -> Void
    func presentExtractList(extract: [ExtractResponse.ExtractData]?) -> Void
}

class UserExtractPresenter: UserExtractPresentationLogic{
    weak var viewController: UserExtractDisplayLogic?
    
    func presentExtractList(extract: [ExtractResponse.ExtractData]?) {
        if let extract = extract {
            self.viewController?.success(extract: extract)
        }
    }
    
    func presentUserAccountData(userAccountData: LoginResponse.UserAccount) {
        self.viewController?.renderUserAccountData(userData: userAccountData)
    }
}
